repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Black (Python formatter)
        language_version: python3
        args: ["--config=pyproject.toml"]
