[tool.black]
line-length = 88
skip-string-normalization = false
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.eggs
  | \.idea
  | build
  | dist
)/
'''
