# Generated by Django 5.2.5 on 2025-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_brokers",
            "0003_alter_transaction_result_amount_alter_wallet_balance",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="destination_iban",
            field=models.CharField(default="test", max_length=34),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_iban",
            field=models.CharField(default="test", max_length=34),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "euro"),
                    ("USD", "dolar amerykański"),
                    ("AUD", "dolar australijski"),
                    ("BGN", "lew (Bułgaria)"),
                    ("BRL", "real (Brazylia)"),
                    ("CAD", "dolar kanadyjski"),
                    ("CHF", "frank szwajcarski"),
                    ("CLP", "peso chilijskie"),
                    ("CNY", "yuan renminbi (Chiny)"),
                    ("CZK", "korona czeska"),
                    ("DKK", "korona duńska"),
                    ("GBP", "funt szterling"),
                    ("HKD", "dolar Hongkongu"),
                    ("HUF", "forint (Węgry)"),
                    ("IDR", "rupia indonezyjska"),
                    ("ILS", "nowy izraelski szekel"),
                    ("INR", "rupia indyjska"),
                    ("ISK", "korona islandzka"),
                    ("JPY", "jen (Japonia)"),
                    ("KRW", "won południowokoreański"),
                    ("MXN", "peso meksykańskie"),
                    ("MYR", "ringgit (Malezja)"),
                    ("NOK", "korona norweska"),
                    ("NZD", "dolar nowozelandzki"),
                    ("PHP", "peso filipińskie"),
                    ("RON", "lej rumuński"),
                    ("SEK", "korona szwedzka"),
                    ("SGD", "dolar singapurski"),
                    ("THB", "bat (Tajlandia)"),
                    ("TRY", "lira turecka"),
                    ("UAH", "hrywna (Ukraina)"),
                    ("XDR", "SDR (MFW)"),
                    ("ZAR", "rand (Republika Południowej Afryki)"),
                ],
                max_length=10,
            ),
        ),
    ]
