# Generated by Django 5.2.5 on 2025-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_brokers",
            "0004_transaction_destination_iban_transaction_source_iban_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="iban",
            field=models.CharField(max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
