# Generated by Django 5.2.5 on 2025-09-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_brokers', '0005_alter_transaction_amount_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'ordering': ['-date', 'currency'],
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
