# Generated by Django 5.2.6 on 2025-09-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_brokers", "0006_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="wallet_status",
            field=models.CharField(default="active", max_length=50),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallets",
                to="backend_brokers.profile",
            ),
        ),
    ]
