# Generated by Django 5.2.6 on 2025-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend_brokers",
            "0008_transaction_visible_to_alter_wallet_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="rate",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
