# Generated by Django 5.2.6 on 2025-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_brokers", "0009_alter_exchangerate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
